"""empty message

Revision ID: 1e4631d74c54
Revises: 3721b83d072d
Create Date: 2024-04-14 19:15:37.337891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e4631d74c54'
down_revision = '3721b83d072d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista_videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_video', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'video', ['id_video'], ['id'])

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_constraint('video_ibfk_1', type_='foreignkey')
        batch_op.drop_column('id_lista')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_lista', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('video_ibfk_1', 'lista_videos', ['id_lista'], ['id'])

    with op.batch_alter_table('lista_videos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_video')

    # ### end Alembic commands ###
