"""empty message

Revision ID: 20e00d20ce2b
Revises: 1e4631d74c54
Create Date: 2024-04-14 19:45:53.954989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20e00d20ce2b'
down_revision = '1e4631d74c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista_videos', schema=None) as batch_op:
        batch_op.drop_constraint('lista_videos_ibfk_3', type_='foreignkey')
        batch_op.drop_column('id_video')

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_lista', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'lista_videos', ['id_lista'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_lista')

    with op.batch_alter_table('lista_videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_video', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('lista_videos_ibfk_3', 'video', ['id_video'], ['id'])

    # ### end Alembic commands ###
