"""empty message

Revision ID: abf2e688ed40
Revises: 20e00d20ce2b
Create Date: 2024-05-08 12:15:18.849339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abf2e688ed40'
down_revision = '20e00d20ce2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista_videos', schema=None) as batch_op:
        batch_op.drop_column('url_lista')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista_videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_lista', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
