"""Initial migration.

Revision ID: e53345604473
Revises: 
Create Date: 2024-04-14 17:31:19.897297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53345604473'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('url_jogo', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lista_favorito',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_lista', sa.String(length=255), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=86), nullable=False),
    sa.Column('email', sa.String(length=84), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lista_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_lista', sa.String(length=255), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_jogo',
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('jogo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jogo'], ['jogo.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], )
    )
    op.create_table('usuario_lista_favorito',
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('lista_favorito', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lista_favorito'], ['lista_favorito.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], )
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('url_video', sa.String(length=255), nullable=False),
    sa.Column('id_lista', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_lista'], ['lista_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('usuario_lista_favorito')
    op.drop_table('usuario_jogo')
    op.drop_table('lista_videos')
    op.drop_table('users')
    op.drop_table('lista_favorito')
    op.drop_table('jogo')
    op.drop_table('categoria')
    # ### end Alembic commands ###
